insert into api_city (city_title) values ('Ekibastuz');
insert into api_city (city_title) values ('Plereyan');
insert into api_city (city_title) values ('Sidrolândia');
insert into api_city (city_title) values ('Mhamid');
insert into api_city (city_title) values ('Lodoyo');
insert into api_city (city_title) values ('Marneuli');
insert into api_city (city_title) values ('Volodarsk');
insert into api_city (city_title) values ('San Juan de Planes');
insert into api_city (city_title) values ('Cachoeira do Sul');
insert into api_city (city_title) values ('Rontu');
insert into api_city (city_title) values ('Piraí do Sul');
insert into api_city (city_title) values ('Bolgar');
insert into api_city (city_title) values ('Xiejiatan');
insert into api_city (city_title) values ('Corona');
insert into api_city (city_title) values ('Parrsboro');
insert into api_city (city_title) values ('Chachagüí');
insert into api_city (city_title) values ('Mahdia');
insert into api_city (city_title) values ('Panggulan');
insert into api_city (city_title) values ('Hanghuadian');
insert into api_city (city_title) values ('Sovetsk');
insert into api_city (city_title) values ('Piekoszów');
insert into api_city (city_title) values ('Qiankou');
insert into api_city (city_title) values ('Ricardo Palma');
insert into api_city (city_title) values ('Babice');
insert into api_city (city_title) values ('Badrah');
insert into api_city (city_title) values ('Kedungbulu');
insert into api_city (city_title) values ('Hedong');
insert into api_city (city_title) values ('Cancela');
insert into api_city (city_title) values ('Bassar');
insert into api_city (city_title) values ('Kovdor');
insert into api_city (city_title) values ('Babakanloa');
insert into api_city (city_title) values ('Dūst Moḩammad Khān');
insert into api_city (city_title) values ('Krasnoznamensk');
insert into api_city (city_title) values ('Aigínio');
insert into api_city (city_title) values ('Cireundang');
insert into api_city (city_title) values ('Angoulême');
insert into api_city (city_title) values ('Липково');
insert into api_city (city_title) values ('Batulawang');
insert into api_city (city_title) values ('Padilla');
insert into api_city (city_title) values ('San Juan');
insert into api_city (city_title) values ('Itumbiara');
insert into api_city (city_title) values ('Pohang');
insert into api_city (city_title) values ('Cikole');
insert into api_city (city_title) values ('Zhongchuan');
insert into api_city (city_title) values ('Szemud');
insert into api_city (city_title) values ('Athmuqam');
insert into api_city (city_title) values ('Linfen');
insert into api_city (city_title) values ('Sabae');
insert into api_city (city_title) values ('Torzhok');
insert into api_city (city_title) values ('Ḩātim');
insert into api_city (city_title) values ('Slobozia');
insert into api_city (city_title) values ('Oslo');
insert into api_city (city_title) values ('Huangtian');
insert into api_city (city_title) values ('Puncaksari');
insert into api_city (city_title) values ('Taokeng');
insert into api_city (city_title) values ('Daduchuan');
insert into api_city (city_title) values ('El Águila');
insert into api_city (city_title) values ('Kandun');
insert into api_city (city_title) values ('Quime');
insert into api_city (city_title) values ('Otacílio Costa');
insert into api_city (city_title) values ('Cahuanuyo');
insert into api_city (city_title) values ('Stanley');
insert into api_city (city_title) values ('Charlotte');
insert into api_city (city_title) values ('Pīr jo Goth');
insert into api_city (city_title) values ('Kalunan');
insert into api_city (city_title) values ('Shuanghe');
insert into api_city (city_title) values ('Karangsumber');
insert into api_city (city_title) values ('Xumu');
insert into api_city (city_title) values ('Santa Rosa');
insert into api_city (city_title) values ('São José do Rio Preto');
insert into api_city (city_title) values ('Reston');
insert into api_city (city_title) values ('Đắk Glei');
insert into api_city (city_title) values ('Boston');
insert into api_city (city_title) values ('Simpang');
insert into api_city (city_title) values ('Matinao');
insert into api_city (city_title) values ('Maindang');
insert into api_city (city_title) values ('Qukës-Skënderbe');
insert into api_city (city_title) values ('Zaleszany');
insert into api_city (city_title) values ('Vorzel’');
insert into api_city (city_title) values ('Iţsā');
insert into api_city (city_title) values ('Goiatuba');
insert into api_city (city_title) values ('Ivoti');
insert into api_city (city_title) values ('Sanchahe');
insert into api_city (city_title) values ('Itapemirim');
insert into api_city (city_title) values ('Meadow Lake');
insert into api_city (city_title) values ('Drachten');
insert into api_city (city_title) values ('Quchomo');
insert into api_city (city_title) values ('Kasba Tadla');
insert into api_city (city_title) values ('Kadugadung');
insert into api_city (city_title) values ('Lishu');
insert into api_city (city_title) values ('Lope de Vega');
insert into api_city (city_title) values ('Saguing');
insert into api_city (city_title) values ('Choujiang');
insert into api_city (city_title) values ('Umeå');
insert into api_city (city_title) values ('El Hermel');
insert into api_city (city_title) values ('Guandi');
insert into api_city (city_title) values ('Carman');
insert into api_city (city_title) values ('Mandráki');
insert into api_city (city_title) values ('Pangu');
insert into api_city (city_title) values ('Ekpoma');
