insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Consumer Services');
insert into api_sector (sector_title) values ('Energy');
insert into api_sector (sector_title) values ('Consumer Services');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Energy');
insert into api_sector (sector_title) values ('Energy');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Energy');
insert into api_sector (sector_title) values ('Health Care');
insert into api_sector (sector_title) values ('Health Care');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Energy');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Health Care');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Consumer Services');
insert into api_sector (sector_title) values ('Health Care');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Consumer Services');
insert into api_sector (sector_title) values ('Public Utilities');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Public Utilities');
insert into api_sector (sector_title) values ('Consumer Services');
insert into api_sector (sector_title) values ('Consumer Non-Durables');
insert into api_sector (sector_title) values ('Transportation');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Health Care');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Consumer Services');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Health Care');
insert into api_sector (sector_title) values ('Miscellaneous');
insert into api_sector (sector_title) values ('Miscellaneous');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Public Utilities');
insert into api_sector (sector_title) values ('Health Care');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Health Care');
insert into api_sector (sector_title) values ('Consumer Services');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Consumer Services');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Capital Goods');
insert into api_sector (sector_title) values ('Technology');
insert into api_sector (sector_title) values ('Energy');
insert into api_sector (sector_title) values ('Public Utilities');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Transportation');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Consumer Durables');
insert into api_sector (sector_title) values ('Public Utilities');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Miscellaneous');
insert into api_sector (sector_title) values ('Consumer Services');
insert into api_sector (sector_title) values ('Health Care');
insert into api_sector (sector_title) values ('Health Care');
insert into api_sector (sector_title) values ('Consumer Durables');
insert into api_sector (sector_title) values ('Consumer Services');
insert into api_sector (sector_title) values ('Public Utilities');
insert into api_sector (sector_title) values ('Basic Industries');
insert into api_sector (sector_title) values ('Public Utilities');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Consumer Services');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Health Care');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Energy');
insert into api_sector (sector_title) values ('Transportation');
insert into api_sector (sector_title) values ('Energy');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Health Care');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Public Utilities');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Consumer Services');
insert into api_sector (sector_title) values ('Technology');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Finance');
insert into api_sector (sector_title) values ('Consumer Services');
insert into api_sector (sector_title) values ('Consumer Services');
insert into api_sector (sector_title) values ('Consumer Durables');
insert into api_sector (sector_title) values ('n/a');
insert into api_sector (sector_title) values ('Consumer Services');
