insert into api_province (province_title) values ('Speech Pathologist');
insert into api_province (province_title) values ('Registered Nurse');
insert into api_province (province_title) values ('Accountant III');
insert into api_province (province_title) values ('Recruiter');
insert into api_province (province_title) values ('Compensation Analyst');
insert into api_province (province_title) values ('VP Accounting');
insert into api_province (province_title) values ('Information Systems Manager');
insert into api_province (province_title) values ('Graphic Designer');
insert into api_province (province_title) values ('Research Assistant II');
insert into api_province (province_title) values ('Food Chemist');
insert into api_province (province_title) values ('Assistant Media Planner');
insert into api_province (province_title) values ('Staff Scientist');
insert into api_province (province_title) values ('Electrical Engineer');
insert into api_province (province_title) values ('Media Manager II');
insert into api_province (province_title) values ('Social Worker');
insert into api_province (province_title) values ('General Manager');
insert into api_province (province_title) values ('Quality Engineer');
insert into api_province (province_title) values ('Nuclear Power Engineer');
insert into api_province (province_title) values ('Account Representative II');
insert into api_province (province_title) values ('Desktop Support Technician');
insert into api_province (province_title) values ('Statistician IV');
insert into api_province (province_title) values ('Professor');
insert into api_province (province_title) values ('Database Administrator IV');
insert into api_province (province_title) values ('Assistant Media Planner');
insert into api_province (province_title) values ('Legal Assistant');
insert into api_province (province_title) values ('Office Assistant IV');
insert into api_province (province_title) values ('Cost Accountant');
insert into api_province (province_title) values ('Desktop Support Technician');
insert into api_province (province_title) values ('Research Nurse');
insert into api_province (province_title) values ('Accounting Assistant I');
insert into api_province (province_title) values ('Technical Writer');
insert into api_province (province_title) values ('Director of Sales');
insert into api_province (province_title) values ('Physical Therapy Assistant');
insert into api_province (province_title) values ('Statistician I');
insert into api_province (province_title) values ('Chemical Engineer');
insert into api_province (province_title) values ('Paralegal');
insert into api_province (province_title) values ('Sales Associate');
insert into api_province (province_title) values ('Human Resources Assistant II');
insert into api_province (province_title) values ('Accountant II');
insert into api_province (province_title) values ('Speech Pathologist');
insert into api_province (province_title) values ('Software Test Engineer IV');
insert into api_province (province_title) values ('Automation Specialist III');
insert into api_province (province_title) values ('Web Designer III');
insert into api_province (province_title) values ('Media Manager I');
insert into api_province (province_title) values ('Health Coach IV');
insert into api_province (province_title) values ('Director of Sales');
insert into api_province (province_title) values ('General Manager');
insert into api_province (province_title) values ('Administrative Officer');
insert into api_province (province_title) values ('Sales Associate');
insert into api_province (province_title) values ('Nuclear Power Engineer');
insert into api_province (province_title) values ('Analog Circuit Design manager');
insert into api_province (province_title) values ('Geological Engineer');
insert into api_province (province_title) values ('Human Resources Assistant I');
insert into api_province (province_title) values ('Chief Design Engineer');
insert into api_province (province_title) values ('Automation Specialist II');
insert into api_province (province_title) values ('Software Test Engineer IV');
insert into api_province (province_title) values ('Sales Associate');
insert into api_province (province_title) values ('Programmer Analyst II');
insert into api_province (province_title) values ('Research Associate');
insert into api_province (province_title) values ('Clinical Specialist');
insert into api_province (province_title) values ('Computer Systems Analyst II');
insert into api_province (province_title) values ('Programmer Analyst III');
insert into api_province (province_title) values ('Systems Administrator IV');
insert into api_province (province_title) values ('Senior Developer');
insert into api_province (province_title) values ('Executive Secretary');
insert into api_province (province_title) values ('Biostatistician III');
insert into api_province (province_title) values ('Design Engineer');
insert into api_province (province_title) values ('Analog Circuit Design manager');
insert into api_province (province_title) values ('Health Coach I');
insert into api_province (province_title) values ('Geologist II');
insert into api_province (province_title) values ('Environmental Specialist');
insert into api_province (province_title) values ('Account Executive');
insert into api_province (province_title) values ('GIS Technical Architect');
insert into api_province (province_title) values ('Mechanical Systems Engineer');
insert into api_province (province_title) values ('Clinical Specialist');
insert into api_province (province_title) values ('Actuary');
insert into api_province (province_title) values ('Data Coordinator');
insert into api_province (province_title) values ('Operator');
insert into api_province (province_title) values ('Computer Systems Analyst IV');
insert into api_province (province_title) values ('Administrative Assistant III');
insert into api_province (province_title) values ('Programmer II');
insert into api_province (province_title) values ('Pharmacist');
insert into api_province (province_title) values ('Legal Assistant');
insert into api_province (province_title) values ('Human Resources Manager');
insert into api_province (province_title) values ('Help Desk Technician');
insert into api_province (province_title) values ('Research Assistant II');
insert into api_province (province_title) values ('Geological Engineer');
insert into api_province (province_title) values ('Budget/Accounting Analyst IV');
insert into api_province (province_title) values ('Sales Representative');
insert into api_province (province_title) values ('Nurse');
insert into api_province (province_title) values ('VP Sales');
insert into api_province (province_title) values ('Software Consultant');
insert into api_province (province_title) values ('Automation Specialist III');
insert into api_province (province_title) values ('Quality Control Specialist');
insert into api_province (province_title) values ('Software Test Engineer III');
insert into api_province (province_title) values ('Food Chemist');
insert into api_province (province_title) values ('Research Associate');
insert into api_province (province_title) values ('Analog Circuit Design manager');
insert into api_province (province_title) values ('Product Engineer');
insert into api_province (province_title) values ('Technical Writer');
