insert into api_category (category_title) values ('Volgograd');
insert into api_category (category_title) values ('Wisconsin Rapids');
insert into api_category (category_title) values ('Chitral');
insert into api_category (category_title) values ('Lüliang');
insert into api_category (category_title) values ('Ji-Paraná');
insert into api_category (category_title) values ('Tonghua');
insert into api_category (category_title) values ('Lordsburg');
insert into api_category (category_title) values ('Wolf Point');
insert into api_category (category_title) values (null);
insert into api_category (category_title) values ('Koromiko');
insert into api_category (category_title) values ('Ranau');
insert into api_category (category_title) values ('Corvera');
insert into api_category (category_title) values ('Copenhagen');
insert into api_category (category_title) values ('Sabu-Sawu Island');
insert into api_category (category_title) values ('Anchorage');
insert into api_category (category_title) values ('Zweibrücken');
insert into api_category (category_title) values ('Ironstone');
insert into api_category (category_title) values ('Klanten flyplass');
insert into api_category (category_title) values ('Xieng Khouang');
insert into api_category (category_title) values ('Huntingburg');
