insert into api_district (district_title) values ('La Roxas');
insert into api_district (district_title) values ('Cosquín');
insert into api_district (district_title) values ('Miami');
insert into api_district (district_title) values ('Colmar');
insert into api_district (district_title) values ('Sangkulirang');
insert into api_district (district_title) values ('João Câmara');
insert into api_district (district_title) values ('Baoxu');
insert into api_district (district_title) values ('Taunoa');
insert into api_district (district_title) values ('Quyangqiao');
insert into api_district (district_title) values ('Kobilje');
insert into api_district (district_title) values ('Efeng');
insert into api_district (district_title) values ('Marseille');
insert into api_district (district_title) values ('Cisaat');
insert into api_district (district_title) values ('Swords');
insert into api_district (district_title) values ('Belford Roxo');
insert into api_district (district_title) values ('Brasília de Minas');
insert into api_district (district_title) values ('Stockholm');
insert into api_district (district_title) values ('Pilar');
insert into api_district (district_title) values ('Cimanglid');
insert into api_district (district_title) values ('Nanmuping');
insert into api_district (district_title) values ('Ancona');
insert into api_district (district_title) values ('Liboro');
insert into api_district (district_title) values ('Mallawī');
insert into api_district (district_title) values ('Valjevo');
insert into api_district (district_title) values ('Beigou');
insert into api_district (district_title) values ('Belén de Umbría');
insert into api_district (district_title) values ('Wola Sernicka');
insert into api_district (district_title) values ('Aleysk');
insert into api_district (district_title) values ('Lambangan Kulon');
insert into api_district (district_title) values ('Chiquinquirá');
insert into api_district (district_title) values ('Iperu');
insert into api_district (district_title) values ('Pleasant Point');
insert into api_district (district_title) values ('Sunzhuang');
insert into api_district (district_title) values ('Qinggang');
insert into api_district (district_title) values ('Hebei');
insert into api_district (district_title) values ('Arrabal');
insert into api_district (district_title) values ('Lae');
insert into api_district (district_title) values ('Montpellier');
insert into api_district (district_title) values ('Verkhnya Rozhanka');
insert into api_district (district_title) values ('Jatobá');
insert into api_district (district_title) values ('Tân Việt');
insert into api_district (district_title) values ('Bromma');
insert into api_district (district_title) values ('Bambas');
insert into api_district (district_title) values ('Junkou');
insert into api_district (district_title) values ('Xiaoqi');
insert into api_district (district_title) values ('Tembang');
insert into api_district (district_title) values ('Mabilog');
insert into api_district (district_title) values ('Fuwah');
insert into api_district (district_title) values ('Panadtaban');
insert into api_district (district_title) values ('Tsagaan-Olom');
insert into api_district (district_title) values ('Álftanes');
insert into api_district (district_title) values ('Ghanzi');
insert into api_district (district_title) values ('Dhamār');
insert into api_district (district_title) values ('Đoan Hùng');
insert into api_district (district_title) values ('Linshanhe');
insert into api_district (district_title) values ('Tiechanggou');
insert into api_district (district_title) values ('Castanheira');
insert into api_district (district_title) values ('Francos');
insert into api_district (district_title) values ('Kulonkali');
insert into api_district (district_title) values ('Szeged');
insert into api_district (district_title) values ('Osiek');
insert into api_district (district_title) values ('Sentani');
insert into api_district (district_title) values ('Nizhniy Novgorod');
insert into api_district (district_title) values ('Salcedo');
insert into api_district (district_title) values ('Nanjing');
insert into api_district (district_title) values ('Pondokkaha Kelod');
insert into api_district (district_title) values ('Troyes');
insert into api_district (district_title) values ('Wólka Pełkińska');
insert into api_district (district_title) values ('Narva');
insert into api_district (district_title) values ('Wichit');
insert into api_district (district_title) values ('Dayan');
insert into api_district (district_title) values ('Shamakhi');
insert into api_district (district_title) values ('Kostanay');
insert into api_district (district_title) values ('Tanalt');
insert into api_district (district_title) values ('Przodkowo');
insert into api_district (district_title) values ('Kramsk');
insert into api_district (district_title) values ('Lebao');
insert into api_district (district_title) values ('Bandjoun');
insert into api_district (district_title) values ('Sredno Konjare');
insert into api_district (district_title) values ('Yangzhuang');
insert into api_district (district_title) values ('Jin’an');
insert into api_district (district_title) values ('Shiwan');
insert into api_district (district_title) values ('Gulou');
insert into api_district (district_title) values ('Aguilares');
insert into api_district (district_title) values ('Podhum');
insert into api_district (district_title) values ('Doropayung');
insert into api_district (district_title) values ('Naili');
insert into api_district (district_title) values ('Dofa');
insert into api_district (district_title) values ('Stari Bohorodchany');
insert into api_district (district_title) values ('Środa Wielkopolska');
insert into api_district (district_title) values ('Ngondokandawu');
insert into api_district (district_title) values ('Harrisburg');
insert into api_district (district_title) values ('Fulong');
insert into api_district (district_title) values ('San Salvador de Jujuy');
insert into api_district (district_title) values ('Letlhakeng');
insert into api_district (district_title) values ('Tuburan');
insert into api_district (district_title) values ('Tanzhesi');
insert into api_district (district_title) values ('Dandu');
insert into api_district (district_title) values ('Grytviken');
insert into api_district (district_title) values ('Jinqiao');
