insert into api_job (job_title) values ('Nurse Practicioner');
insert into api_job (job_title) values ('Assistant Media Planner');
insert into api_job (job_title) values ('Teacher');
insert into api_job (job_title) values ('Director of Sales');
insert into api_job (job_title) values ('Desktop Support Technician');
insert into api_job (job_title) values ('Director of Sales');
insert into api_job (job_title) values ('Engineer III');
insert into api_job (job_title) values ('Graphic Designer');
insert into api_job (job_title) values ('Electrical Engineer');
insert into api_job (job_title) values ('Account Coordinator');
insert into api_job (job_title) values ('Software Consultant');
insert into api_job (job_title) values ('Marketing Manager');
insert into api_job (job_title) values ('Senior Financial Analyst');
insert into api_job (job_title) values ('Structural Analysis Engineer');
insert into api_job (job_title) values ('Software Consultant');
insert into api_job (job_title) values ('Professor');
insert into api_job (job_title) values ('Teacher');
insert into api_job (job_title) values ('Help Desk Technician');
insert into api_job (job_title) values ('Sales Representative');
insert into api_job (job_title) values ('Administrative Assistant I');
insert into api_job (job_title) values ('Desktop Support Technician');
insert into api_job (job_title) values ('VP Marketing');
insert into api_job (job_title) values ('Software Engineer II');
insert into api_job (job_title) values ('Recruiter');
insert into api_job (job_title) values ('Senior Editor');
insert into api_job (job_title) values ('Tax Accountant');
insert into api_job (job_title) values ('Developer IV');
insert into api_job (job_title) values ('Community Outreach Specialist');
insert into api_job (job_title) values ('Chemical Engineer');
insert into api_job (job_title) values ('Operator');
insert into api_job (job_title) values ('Payment Adjustment Coordinator');
insert into api_job (job_title) values ('Community Outreach Specialist');
insert into api_job (job_title) values ('Senior Cost Accountant');
insert into api_job (job_title) values ('Web Developer I');
insert into api_job (job_title) values ('Physical Therapy Assistant');
insert into api_job (job_title) values ('Product Engineer');
insert into api_job (job_title) values ('Clinical Specialist');
insert into api_job (job_title) values ('Social Worker');
insert into api_job (job_title) values ('Nurse');
insert into api_job (job_title) values ('Professor');
insert into api_job (job_title) values ('Legal Assistant');
insert into api_job (job_title) values ('Senior Cost Accountant');
insert into api_job (job_title) values ('Senior Financial Analyst');
insert into api_job (job_title) values ('Desktop Support Technician');
insert into api_job (job_title) values ('Director of Sales');
insert into api_job (job_title) values ('Health Coach III');
insert into api_job (job_title) values ('Nurse');
insert into api_job (job_title) values ('Compensation Analyst');
insert into api_job (job_title) values ('Research Nurse');
insert into api_job (job_title) values ('Physical Therapy Assistant');
insert into api_job (job_title) values ('Senior Sales Associate');
insert into api_job (job_title) values ('Financial Analyst');
insert into api_job (job_title) values ('Sales Associate');
insert into api_job (job_title) values ('Senior Editor');
insert into api_job (job_title) values ('Staff Accountant I');
insert into api_job (job_title) values ('Assistant Media Planner');
insert into api_job (job_title) values ('Cost Accountant');
insert into api_job (job_title) values ('Geological Engineer');
insert into api_job (job_title) values ('Electrical Engineer');
insert into api_job (job_title) values ('Executive Secretary');
insert into api_job (job_title) values ('Accountant II');
insert into api_job (job_title) values ('Occupational Therapist');
insert into api_job (job_title) values ('Mechanical Systems Engineer');
insert into api_job (job_title) values ('Quality Engineer');
insert into api_job (job_title) values ('Dental Hygienist');
insert into api_job (job_title) values ('Tax Accountant');
insert into api_job (job_title) values ('Recruiter');
insert into api_job (job_title) values ('Structural Engineer');
insert into api_job (job_title) values ('VP Accounting');
insert into api_job (job_title) values ('Research Associate');
insert into api_job (job_title) values ('Human Resources Manager');
insert into api_job (job_title) values ('Business Systems Development Analyst');
insert into api_job (job_title) values ('Pharmacist');
insert into api_job (job_title) values ('Assistant Media Planner');
insert into api_job (job_title) values ('Compensation Analyst');
insert into api_job (job_title) values ('Quality Control Specialist');
insert into api_job (job_title) values ('Registered Nurse');
insert into api_job (job_title) values ('Computer Systems Analyst IV');
insert into api_job (job_title) values ('Director of Sales');
insert into api_job (job_title) values ('GIS Technical Architect');
insert into api_job (job_title) values ('VP Quality Control');
insert into api_job (job_title) values ('Quality Control Specialist');
insert into api_job (job_title) values ('Help Desk Technician');
insert into api_job (job_title) values ('Technical Writer');
insert into api_job (job_title) values ('Computer Systems Analyst III');
insert into api_job (job_title) values ('Financial Advisor');
insert into api_job (job_title) values ('Analyst Programmer');
insert into api_job (job_title) values ('Senior Financial Analyst');
insert into api_job (job_title) values ('Editor');
insert into api_job (job_title) values ('Social Worker');
insert into api_job (job_title) values ('Sales Associate');
insert into api_job (job_title) values ('Executive Secretary');
insert into api_job (job_title) values ('Graphic Designer');
insert into api_job (job_title) values ('Dental Hygienist');
insert into api_job (job_title) values ('Librarian');
insert into api_job (job_title) values ('Internal Auditor');
insert into api_job (job_title) values ('Registered Nurse');
insert into api_job (job_title) values ('Executive Secretary');
insert into api_job (job_title) values ('Legal Assistant');
insert into api_job (job_title) values ('Research Associate');
